# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.15
    
    working_directory: ~/repo

    steps:
      - checkout
      - run: "npm install"
      - run: "npm run build"
  test:
    docker:
      - image: circleci/node:8.15
    steps:
      - checkout
      - run: "npm run test"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
